config/routes.rb
Rails.application.routes.draw do
  
  get 'carts/index', to: 'carts#index'
  get 'orders/index', to: 'orders#index'
  get 'orders/show/:id', to: 'orders#show', as: 'order'
  get 'orders/update_order_item', to: 'orders#update_order_item'
  get 'sellers/order_list', to: 'sellers#order_list', as: 'order_list'
  post 'orders/create', to: 'orders#create'
  devise_for :users, controllers: {
    registrations: 'customers/registrations'
  }
  
  devise_scope :user do
    root to: "products#index"
  end
  resources :sellers
  resources :customers
  resources :products do
    member do
      get '/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'
      delete '/remove_from_cart', to: 'products#remove_from_cart', as: 'remove_from_cart'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :order_items, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :customer
    belongs_to :product
end

app/models/customer.rb
class Customer < User
    has_many :orders
    has_many :carts
    has_many :products, through: :carts
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_items
    has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :order
    enum status: { pending: 'pending', shipped: 'shipped',cancel: 'cancel' ,delivered: 'delivered',refunded: 'refunded' }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :carts
  has_many :customers, through: :carts
end

app/models/seller.rb
class Seller < User
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def customer?
    type == 'Customer'
  end
  def seller?
    type == 'Seller'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :type])
    end
    def after_sign_in_path_for(resource)
        if resource.type.eql?('Seller')
            sellers_url
        else 
            products_url
        end
    end
end
  

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @products = current_user.carts.map(&:product)
    @order = Order.all
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
  end

  def update
    order_item = OrderItem.find(params[:id])
    order_item.update(status: params[:status])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    #@order_item = current_user.orders.map(&:order_items)
    #byebug
    @orders = current_user.orders
    
  end
  def show
    order= Order.find(params[:id])
    @products = order.products
  end
  def new    
  end

  def create
    p_ids = params[:product_ids].split(' ')
    @order = current_user.orders.new(
      amount: Product.find(p_ids).sum(&:product_amount),
      paid_status: paid_status
      )
      p_ids.each do |p_id|
      @order.order_items << OrderItem.new(product_id: p_id)
    end 
    #o.where(:paid_status => false)
    #o.pending!
    @order.save                 
    clear_cart                                                          
    redirect_to carts_index_path
  end
  def update_order_item
    order_item = OrderItem.find(params[:order_item_id])
    order_item.update(status: params[:order_item][:status])
    redirect_to order_list_path
  end
  private
  def clear_cart
    current_user.carts.destroy_all
  end
  def paid_status
    !(params[:order] &&  params[:order][:paid_status])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: %i[ index show]
  # GET /products or /products.json
  def index
    @products = Product.all
    @product = Product.new
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /products/1/edit
  def edit
    current_user.products.find(params[:id])
    authorize Product
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.new(product_params)
    authorize @product
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end

  end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    current_user.products.find(params[:id])
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    authorize @product
    current_user.products.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: "Product was successfully destroyed." }
    end
  end
  def add_to_cart
    cart = current_user.carts.new
    cart.product_id = params[:id]
    cart.save
    redirect_to products_path
  end
  def remove_from_cart
    cart = current_user.carts.where(product_id: params[:id]).first
    cart.destroy
    redirect_to products_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:user_id, :product_name, :product_amount, :product_info)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
    def index
        @products = current_user.products
    end
    def order_list
        @products = current_user.products.joins(:order_items)
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/carts/index.html.erb
<h1>Cart</h1>
<table>
  <thead>
    <tr>  
      <th>Product name</th>
      <th>Product amount</th>
      <th>Product info</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_amount %></td>
        <td><%= product.product_info %></td>
        <td><%= link_to 'Show', product %></td>
        <td>
          <% if current_user.carts.where(product_id: product.id).present? %>
            <%= button_to 'Remove_from_cart', remove_from_cart_product_path(product), method: 'delete'  %></td>
          <% end %>
         </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= form_for Order.new, url: orders_create_path  do |f|  %>
  <div class="fields">
    <%= f.label "Paid" %>
    <%#= f.check_box :paid_status, {}, true, false %>
    <%= f.check_box(:paid_status, options = {:checked => true}, checked_value =  true, unchecked_value = false) %>  
    <br>
    <%= hidden_field_tag :product_ids, @products.pluck(:id) %>
  </div>
  <% if @products.present? %>
    <div class="actions">
      <%= f.submit "Place Order", class: "button small radius" %>
    </div>
    <% end %>
<% end %>

<%= link_to 'back', root_path %>

app/views/order_items/index.html.erb
<h1>Ordered Items</h1>

<%= link_to 'back', sellers_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<table>
  <thead>
    <tr>  
      <th>Order Id</th>
      <th>Total amount</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order|%>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.amount %></td>
        <% if order.paid_status? %>
          <td>Unpaid</td>
        <% else %>
          <td>Paid</td>
        <% end %>
        <td> <%= link_to 'Show Products', order_path(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<p>  </p>
<%= link_to 'back', root_path %>

app/views/orders/show.html.erb
<table>
  <thead>
    <tr>  
      <th>Product name</th>
      <th>Product amount</th>
      <th>Product info</th>
      <th>Shipping</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_amount %></td>
        <td><%= product.product_info %></td>
        <td><%=  product.order_items.first.status%></td>
        <td><%= link_to 'Show', product %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'back', root_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :product_amount %>
    <%= form.number_field :product_amount %>
  </div>

  <div class="field">
    <%= form.label :product_info %>
    <%= form.text_field :product_info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> 
<%= link_to 'Back', sellers_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table>
  <thead>
    <tr>  
      <th>Product name</th>
      <th>Product amount</th>
      <th>Product info</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_amount %></td>
        <td><%= product.product_info %></td>
        <td><%= link_to 'Show', product %></td>
        <td>
        <% if user_signed_in? && current_user.type == 'Customer'%>
          <% if current_user.carts.where(product_id: product.id).present? %>
            <%= button_to 'Remove_from_cart', remove_from_cart_product_path(product), method: 'delete'  %></td>
          <% else %>
            <%= button_to 'Add_to_cart', add_to_cart_product_path(product), method: 'get' %>
          <% end %>
        <% end %>  
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_product_path(product) if policy(product).edit? %></td>
          <td><%= button_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } if policy(product).destroy? %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if user_signed_in? && current_user.type == 'Customer'%>
  <%= link_to 'Cart', carts_index_path %>
  <p>  </p>
  <%= link_to 'Your Orders', orders_index_path %>
<% end %>    
<% if user_signed_in? && policy(@product).new? %>
  <%= link_to 'New Product', new_product_path(@product) %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', sellers_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product amount:</strong>
  <%= @product.product_amount %>
</p>

<p>
  <strong>Product info:</strong>
  <%= @product.product_info %>
</p>
<% if user_signed_in? && policy(@product).edit? %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>

<% if user_signed_in? && current_user.type == 'Customer'%>
  <%= link_to 'Back',  root_path %>
<%else%>
  <%= link_to 'Back',  sellers_path %>
<%end%>

app/views/sellers/index.html.erb
<h2>Seller Login</h2>
<style>
  body {
        margin:50px 0px; padding:0px;
        text-align:center;
        align:center;
  }
  .field {
    font-family: "Times New Roman", Times, serif;
  }
  label,input {
    color: red;
  }
  label {
    color: violet;
  }
  br {
    clear: left;
  }
  h2 {
    color: green;
  }
</style>
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<body>
<table>
  <thead>
    <tr>  
      <th>Product name</th>
      <th>Product amount</th>
      <th>Product info</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_amount %></td>
        <td><%= product.product_info %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= button_to 'Destroy', product_path(product), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>  
<body>
    <%= link_to 'New Product', new_product_path %>
    <%= link_to 'Orders', order_list_path %>
</body>

app/views/sellers/order_list.html.erb
<h2>ordered item</h2>
<table>
  <thead>
    <tr>  
      <th>Product name</th>
      <th>Amount</th>
      <th>info</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  <% @products .each do |product|%>
    <tr order_item_id= <%= product.order_items.first.id %> >
        <td><%= product.product_name %></td>
        <td><%= product.product_amount %></td>
        <td><%= product.product_info %></td> 
        <td>
          <%#= select_tag("order_item[status]", options_for_select(OrderItem.statuses, product.order_items.first.status), class:'order-item-status-change') %>
          <%= form_tag("/orders/update_order_item", method: "get") do %>
            <%= select_tag "order_item[status]", options_for_select( OrderItem.statuses, product.order_items.first.status) %>
            <%= hidden_field_tag :order_item_id , product.order_items.first.id %>
            <%= submit_tag("Update") %>
          <% end %>
        </td>
     </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', sellers_path %>